name: deploy

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      # Agrega aquí los pasos de tu acción

      # Este ejemplo solo imprime un mensaje
      - name: Ejecutar acción
        run: echo "Esta acción se ejecutará en rama main"
